services:
  webserver:
    image: bouzomgi/chatter-fe
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    volumes:
      - ./private/cert:/etc/cert:ro
    networks:
      - chatter-network

networks:
  chatter-network:
    driver: bridge
