services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_HTTP_ENDPOINT=${REACT_APP_BACKEND_HTTP_ENDPOINT}
      - REACT_APP_BACKEND_WEBSOCKET_ENDPOINT=${REACT_APP_BACKEND_HTTP_ENDPOINT}
    stdin_open: true
    tty: true
    networks:
      - chatter-network

networks:
  chatter-network:
    driver: bridge
