services:
  webserver:
    image: bouzomgi/chatter-fe
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    networks:
      - chatter-network

networks:
  chatter-network:
    driver: bridge
