name: 'Deploy'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deployment]
  push:
    branches: main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Create Production Build
        run: CI='' npm run build
        env:
          REACT_APP_BACKEND_HTTP_ENDPOINT: ${{ vars.REACT_APP_BACKEND_HTTP_ENDPOINT }}
          REACT_APP_BACKEND_WEBSOCKET_ENDPOINT: ${{ vars.REACT_APP_BACKEND_WEBSOCKET_ENDPOINT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gha-deployment
          aws-region: us-east-1

      - name: Sync webserver build to S3
        run: aws s3 sync ./build s3://chatter-webserver

      - name: Find Cloudfront distribution id
        id: get-id
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?contains(@, 'chitchatter.link')]].Id | [0]" --output text)
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Error: No CloudFront distribution ID found. Exiting with failure."
            exit 1
          fi
          echo "::set-output name=distribution-id::$DISTRIBUTION_ID"

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ steps.get-id.outputs.distribution-id }} --paths "/*"

      - name: Run Integration Tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.prod.ts
