name: 'Deploy'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deployment]
  push:
    branches: main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Create Production Build
        run: CI='' npm run build
        env:
          REACT_APP_BACKEND_ENDPOINT: ${{ vars.REACT_APP_BACKEND_ENDPOINT }}
          REACT_APP_BACKEND_WEBSOCKET_ENDPOINT: ${{ vars.REACT_APP_BACKEND_WEBSOCKET_ENDPOINT }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bouzomgi
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t bouzomgi/chatter-fe:latest .

      - name: Push Docker image
        run: |
          docker push bouzomgi/chatter-fe:latest
