name: 'Deploy'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deployment]
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Print version
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bouzomgi
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/arm64/v8 \
            -t bouzomgi/chatter-fe:latest \
            -t bouzomgi/chatter-fe:${{ steps.gitversion.outputs.MajorMinorPatch }} \
            --push .

      - name: Tag commit if Docker image built
        if: success() # only runs if the previous step succeeded
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.gitversion.outputs.MajorMinorPatch }} $GITHUB_SHA
          git push origin v${{ steps.gitversion.outputs.MajorMinorPatch }}
