name: 'PR'
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  on-pr:
    runs-on: 'ubuntu-latest'
    environment: test
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.x
          cache: npm

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          # just perform install
          runTests: false

      - name: Check Lint
        run: npm run check-lint

      - name: Run local Cypress tests
        run: npm run test:local:ci
        env:
          REACT_APP_BACKEND_ENDPOINT: ${{ vars.REACT_APP_BACKEND_ENDPOINT }}
          REACT_APP_BACKEND_WEBSOCKET_ENDPOINT: ${{ vars.REACT_APP_BACKEND_WEBSOCKET_ENDPOINT }}
